name: build-pwnbox-on-commit

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push (full)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            deadpackets/pwnbox:latest
            ghcr.io/deadpackets/pwnbox:latest
            deadpackets/pwnbox:full
            ghcr.io/deadpackets/pwnbox:full
      -
        name: Build and push (light)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            NO_PIP_INSTALL='yes'
            NO_PYTHON_INSTALL='yes'
            NO_WORDLISTS='yes'
          tags: |
            deadpackets/pwnbox:light
            ghcr.io/deadpackets/pwnbox:light
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: deadpackets/pwnbox