name: build-pwnbox-on-commit

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"
      -
        name: Get Current Tag
        id: currentTag
        uses: olegtarasov/get-tag@v2.1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push (full)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.date }}
            BUILD_VERSION=${{ steps.currentTag.outputs.tag }}
            VCF_REF=${GITHUB_SHA::8}
          tags: |
            deadpackets/pwnbox:latest
            ghcr.io/deadpackets/pwnbox:latest
            deadpackets/pwnbox:${{ steps.currentTag.outputs.tag }}
            ghcr.io/deadpackets/pwnbox:${{ steps.currentTag.outputs.tag }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: deadpackets/pwnbox
      -
        name: Update VERSION.txt
        run: |
          echo "${{ steps.currentTag.outputs.tag }}" > VERSION.txt
      -
        name: Push the updated VERSION.txt
        uses: EndBug/add-and-commit@v7
        with:
          add: 'VERSION.txt'
          author_name: Github Action
          author_email: action@github.com
          message: '[GitHub Action] Update VERSION.txt'
          branch: main
          push: true
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: 'main'
