name: build-pwnbox-on-commit

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"
      -
        name: Get Current Tag
        uses: olegtarasov/get-tag@v2.1
        id: currentTag
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: 'main'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push (full)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args:
            BUILD_DATE=${{ steps.vars.outputs.date }}
            BUILD_VERSION=${{ steps.currentTag.outputs.tag }}
            VCF_REF=${GITHUB_SHA::8}
          tags: |
            deadpackets/pwnbox:latest
            ghcr.io/deadpackets/pwnbox:latest
            deadpackets/pwnbox:full
            ghcr.io/deadpackets/pwnbox:full
      -
        name: Build and push (light)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            NO_PIP_INSTALL='yes'
            NO_PYTHON_INSTALL='yes'
            NO_WORDLISTS='yes'
            BUILD_DATE=${{ steps.vars.outputs.date }}
            BUILD_VERSION=${{ steps.currentTag.outputs.tag }}
            VCF_REF=${GITHUB_SHA::8}
          tags: |
            deadpackets/pwnbox:light
            ghcr.io/deadpackets/pwnbox:light
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: deadpackets/pwnbox