name: build-pwnbox-on-commit

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"
      -
        name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      -
        name: Bump version
        id: semver
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          verion: ${{ steps.previoustag.outputs.tag }}
      -
        name: Update files
        run: |
          echo "# PwnBox - ${{ steps.semver.outputs.tag }}\nWeekly update." > CHANGELOG.md
      -
        name: Push the updated files
        uses: EndBug/add-and-commit@v7
        with:
          add: "CHANGELOG.md"
          author_name: Github Action
          author_email: action@github.com
          message: '[GitHub Action] Weekly Update'
          tag: "${{ steps.semver.outputs.tag }} --force"